[package]
name = "beacon"
version = "0.1.0"
edition = "2024"
description = "A lightweight status line generator for Claude Code"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
