[package]
name = "beacon-cli"
version = "0.0.1"
edition = "2024"

[dependencies]
beacon-core = { path = "../beacon-core" }
clap = { version = "4.5.45", features = ["derive"] }
anyhow = "1.0.99"

[[bin]]
name = "beacon-cli"
path = "src/main.rs"
