name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  check:
    name: Lint, Build, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: System deps (git2 / openssl)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libssl-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: rustfmt check
        run: cargo fmt --all -- --check

      - name: clippy (deny warnings)
        run: cargo clippy --locked --workspace --all-targets -- -D warnings

      - name: Build (release)
        run: cargo build --locked --workspace --release --verbose

      - name: Test (workspace)
        run: cargo test --locked --workspace -- --nocapture

      - name: Build docs
        run: cargo doc --locked --no-deps

  bench:
    name: Bench threshold gate
    runs-on: ubuntu-latest
    needs: check
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: System deps (git2 / openssl)
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends pkg-config libssl-dev

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Run bench check (mean < 50ms)
        run: make bench-check
